In [3]:
import torch

# Create a tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]],dtype = torch.float32)


tensor([2.5000, 3.5000, 4.5000])


In [4]:
tensor.shape

torch.Size([2, 3])

In [6]:

# Calculate the mean along rows
mean_row = tensor.mean(dim=0)
print(mean_row)
print(mean_row.shape)

# [2.5, 3.5, 4.5]


tensor([2.5000, 3.5000, 4.5000])
torch.Size([3])


In [8]:
mean_row_with_keepdims = tensor.mean(dim=0, keepdims=True)
print(mean_row_with_keepdims)
print(mean_row_with_keepdims.shape)


tensor([[2.5000, 3.5000, 4.5000]])
torch.Size([1, 3])


In [9]:
centered_tensor = tensor - mean_row_with_keepdims
print(centered_tensor)


tensor([[-1.5000, -1.5000, -1.5000],
        [ 1.5000,  1.5000,  1.5000]])


In [10]:
centered_tensor_no_keep = tensor - mean_row
print(centered_tensor_no_keep)

tensor([[-1.5000, -1.5000, -1.5000],
        [ 1.5000,  1.5000,  1.5000]])
