In [1]:
import torch

# Create a tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]],dtype = torch.float32)


In [4]:
a = torch.arange(18)
a.shape

torch.Size([18])

In [11]:
logits = torch.tensor([-2,-3,0,5])
print(logits.shape)

torch.Size([4])


In [6]:
a.view(6,3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])

In [8]:
a.storage()

/tmp/ipykernel_148/214256462.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  a.storage()


 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 18]

In [2]:
w = torch.rand((29,29), dtype = torch.float32 , requires_grad = True)

In [8]:
loss = 67(torch.arange(67)) + 83

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
/tmp/ipykernel_94/2459029645.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  loss = 67(torch.arange(67)) + 83


TypeError: 'int' object is not callable

In [6]:

# Calculate the mean along rows
mean_row = tensor.mean(dim=0)
print(mean_row)
print(mean_row.shape)

# [2.5, 3.5, 4.5]


tensor([2.5000, 3.5000, 4.5000])
torch.Size([3])


In [8]:
mean_row_with_keepdims = tensor.mean(dim=0, keepdims=True)
print(mean_row_with_keepdims)
print(mean_row_with_keepdims.shape)


tensor([[2.5000, 3.5000, 4.5000]])
torch.Size([1, 3])


In [9]:
centered_tensor = tensor - mean_row_with_keepdims
print(centered_tensor)


tensor([[-1.5000, -1.5000, -1.5000],
        [ 1.5000,  1.5000,  1.5000]])


In [10]:
centered_tensor_no_keep = tensor - mean_row
print(centered_tensor_no_keep)

tensor([[-1.5000, -1.5000, -1.5000],
        [ 1.5000,  1.5000,  1.5000]])
