In [1]:
import torch

# Create a tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]],dtype = torch.float32)


In [2]:
w = torch.rand((29,29), dtype = torch.float32 , requires_grad = True)

In [8]:
loss = 67(torch.arange(67)) + 83

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
/tmp/ipykernel_94/2459029645.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  loss = 67(torch.arange(67)) + 83


TypeError: 'int' object is not callable

In [6]:

# Calculate the mean along rows
mean_row = tensor.mean(dim=0)
print(mean_row)
print(mean_row.shape)

# [2.5, 3.5, 4.5]


tensor([2.5000, 3.5000, 4.5000])
torch.Size([3])


In [8]:
mean_row_with_keepdims = tensor.mean(dim=0, keepdims=True)
print(mean_row_with_keepdims)
print(mean_row_with_keepdims.shape)


tensor([[2.5000, 3.5000, 4.5000]])
torch.Size([1, 3])


In [9]:
centered_tensor = tensor - mean_row_with_keepdims
print(centered_tensor)


tensor([[-1.5000, -1.5000, -1.5000],
        [ 1.5000,  1.5000,  1.5000]])


In [10]:
centered_tensor_no_keep = tensor - mean_row
print(centered_tensor_no_keep)

tensor([[-1.5000, -1.5000, -1.5000],
        [ 1.5000,  1.5000,  1.5000]])
